name: smart_yoga_mat_app
description: A mobile app for controlling and showcasing features of a smart yoga mat.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies for data storage and real-time updates
  firebase_core: ^2.8.0
  cloud_firestore: ^4.14.0
  audioplayers: ^5.2.1

  # For Bluetooth connectivity
  flutter_blue: ^0.8.0

  # For handling OTA updates (using HTTP requests)
  http: ^1.1.0

  # For state management (Provider pattern)
  provider: ^6.0.5

  # Additional UI and state management
  flutter_switch: ^0.3.2 # for toggle switches
  shared_preferences: ^2.1.1 # updated for better compatibility with Flutter SDK

  # Optional: Analytics (if needed for logging events, Firebase Analytics recommended)
  firebase_analytics: ^10.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/yoga_mat.png
    - assets/breathing.mp3
    - assets/ocean_waves.mp3
    - assets/ambient_music.mp3
    - assets/breathing_image.jpg
    - assets/ocean_waves_image.jpg
    - assets/ambient_music_image.jpg
